# Cloudflare Pages Configuration
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "dhi13man-portfolio-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"
